version: '3.4'

services:
  mongo:
    image: mongo
    command: mongod --port 28000
    ports:
      - 28000:28000
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${ROOT_DATABASE}
  # mongo-seed:
  #   image: stefanwalther/mongo-seed
  #   container_name: mongo-seed
  #   environment:
  #     - MONGODB_HOST=mongo
  #     - MONGODB_PORT=28000
  #   volumes:
  #     - ./mongo-seed:/data
  #   depends_on:
  #     - mongo
  #   command: >
  #     mongoimport --host mongo --port 28000 --db genesis --mode upsert --type json --file /data/entityDNs.json --jsonArray
  #     && mongoimport --host mongo --port 28000 --db genesis --mode upsert --type json --file /data/digitalIdentitiesDNs.json --jsonArray
  #     && mongoimport --host mongo --port 28000 --db genesis --mode upsert --type json --file /data/roleDNs.json --jsonArray
  #     && mongoimport --host mongo --port 28000 --db genesis --mode upsert --type json --file /data/organizationGroupsDNs.json --jsonArray

  feature:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo
      MONGO_FEATURE_COLLECTION_NAME: feature
      RABBIT_URI: amqp://rabbit
