version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${ROOT_DATABASE}
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  feature:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo
      MONGO_FEATURE_COLLECTION_NAME: feature
      RABBIT_URI: amqp://rabbit
